site_name: telepath - Documentation
repo_url: https://github.com/wagtail/telepath
edit_uri: blob/main/docs/
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'indigo'
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Packing external objects: adapters.md
  - Packing objects to primitive values: primitive_adapters.md
  - API reference: api_reference.md
  - Data format: data_format.md
