
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

# Current configuration:
# - django 2.2, python 3.6
# - django 3.0, python 3.7
# - django 3.1, python 3.8
# - django 3.2, python 3.9
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - python: 3.6
            django: "Django>=2.2,<2.3"
            experimental: false
          - python: 3.7
            django: "Django>=3.0,<3.1"
            experimental: false
          - python: 3.8
            django: "Django>=3.1,<3.2"
            experimental: false
          - python: 3.9
            django: "Django>=3.2,<3.3"
            experimental: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "${{ matrix.django }}"
          pip install -e .
      - name: Test
        run: django-admin test --settings=telepath.test_settings
