
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

# Current configuration:
# - django 3.2, python 3.8
# - django 4.0, python 3.8
# - django 4.1, python 3.9
# - django 4.2, python 3.10
# - django main, python 3.11
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - python: "3.8"
            django: "Django>=3.2,<3.3"
            experimental: false
          - python: "3.8"
            django: "Django>=4.0,<4.1"
            experimental: false
          - python: "3.9"
            django: "Django>=4.1,<4.2"
            experimental: false
          - python: "3.10"
            django: "Django>=4.2,<4.3"
            experimental: false
          - python: "3.11"
            django: "git+https://github.com/django/django.git@main#egg=Django"
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "${{ matrix.django }}"
          pip install -e .
      - name: Test
        run: django-admin test --settings=telepath.test_settings
